// Shared RPC contract between the Bun main process and the Vue webview.
//
// The `bun.requests` half lists every command the frontend can invoke
// (the rough equivalent of the Tauri `CommandMap`); `bun.messages` are
// fire-and-forget pushes from bun to the webview — we use a single
// `sessionEvent` channel and route by `sessionId` on the frontend,
// replacing Tauri's per-session `Channel<SessionEventPayload>`.
//
// Keep this file the single source of truth — both `src-bun/index.ts`
// and `src/ipc/invoke.ts` import the type from here.

import type { RPCSchema } from "electrobun/bun";
import type { AppErrorPayload } from "./app/errors";

export type ThemeChoice = "system" | "light" | "dark";
export type ReasoningVisibility = "hidden" | "compact" | "expanded";

/// Agent run mode, mirrors the SDK `SessionMode` union.
/// "interactive" prompts for permission per action; "plan" stays in
/// read-only planning mode; "autopilot" runs unattended.
export type SessionMode = "interactive" | "plan" | "autopilot";

export interface SessionHistoryCompactionResult {
	/// Whether compaction completed successfully.
	success: boolean;
	/// Tokens freed by compaction (when available).
	tokensFreed: number | null;
	/// Number of messages removed during compaction (when available).
	messagesRemoved: number | null;
}

export interface Appearance {
	theme: ThemeChoice;
	reasoningVisibility: ReasoningVisibility;
}

export interface Settings {
	version: number;
	appearance: Appearance;
	/// Persisted layout state. Only the dockview JSON is stored here —
	/// session content (transcripts, tool calls, …) lives CLI-side and
	/// is rehydrated via `client.resumeSession()` on startup. The
	/// dockview JSON is opaque to us; we never inspect or mutate it
	/// directly, just hand it back to `api.fromJSON()`.
	layout: Layout;
	/// Workspace MRU. Populated by the topbar's path input every time
	/// a session is successfully created with a non-empty
	/// `workingDirectory`. The most-recently-used path is at index 0.
	workspaces: Workspaces;
}

export interface Layout {
	/// Serialized dockview state (`api.toJSON()`). `null` means
	/// "no panes were open last time" — start with an empty dockview.
	dockview: unknown | null;
}

export interface Workspaces {
	/// Most-recently-used absolute filesystem paths the user has spun
	/// sessions in. Capped at WORKSPACES_MRU_LIMIT (10) entries; head
	/// of the list is the most recent. Persisted as-is so the topbar
	/// AutoComplete can suggest from prior runs.
	recent: string[];
}

export interface ModelSummary {
	id: string;
	name: string;
	supportsReasoningEffort: boolean;
	supportedReasoningEfforts: string[];
	defaultReasoningEffort: string | null;
}

/// Summary of a CLI-side session, surfaced to the frontend for the
/// "recent sessions" picker and for startup-resume. Dates are
/// stringified (ISO 8601) so the wire payload is JSON-safe — the SDK
/// hands us `Date` objects but the RPC bridge will lose the type tag.
export interface SessionMetadataSummary {
	sessionId: string;
	startTime: string;
	modifiedTime: string;
	summary?: string;
	isRemote: boolean;
	cwd?: string;
	repository?: string;
	branch?: string;
}

/// Wire-format for a single SDK session event.
/// `eventType` mirrors the SDK's discriminated-union `type` field; `data`
/// carries the full event object verbatim so the frontend can pick out
/// event-specific fields without us hand-mirroring every variant.
/// `agentId` / `eventId` / `timestamp` are lifted off the SDK envelope so
/// the frontend can correlate sub-agent activity and order events without
/// us mirroring every variant's metadata into `data`.
export interface SessionEventPayload {
	sessionId: string;
	eventType: string;
	data: Record<string, unknown>;
	/// Sub-agent instance identifier. Absent for events from the
	/// root/main agent and session-level events.
	agentId?: string;
	/// UUID v4 generated by the SDK when the event is emitted.
	eventId?: string;
	/// ISO 8601 timestamp from the SDK envelope.
	timestamp?: string;
}

export type DafmanRPC = {
	bun: RPCSchema<{
		requests: {
			createClient: { params: Record<string, never>; response: string };
			createSession: {
				/// `workingDirectory` is the absolute filesystem path the
				/// SDK uses as `cwd` for all tool invocations in this
				/// session. Empty / omitted falls back to the bun
				/// process's cwd (the SDK's own default).
				params: { workingDirectory?: string };
				response: string;
			};
			/// Native folder picker. Returns the absolute path of the
			/// chosen directory, or `null` if the user cancelled.
			pickFolder: {
				params: { startingFolder?: string };
				response: string | null;
			};
			disconnectSession: {
				params: { sessionId: string };
				response: string;
			};
			sendMessage: {
				params: { sessionId: string; text: string };
				response: string;
			};
			listModels: {
				params: Record<string, never>;
				response: ModelSummary[];
			};
			setSessionModel: {
				params: {
					sessionId: string;
					model: string;
					reasoningEffort: string | null;
				};
				response: string;
			};
			resumeSession: {
				params: {
					sessionId: string;
					model: string | null;
					reasoningEffort: string | null;
				};
				response: string;
			};
			listSessions: {
				params: Record<string, never>;
				response: SessionMetadataSummary[];
			};
			getSessionMode: {
				params: { sessionId: string };
				response: SessionMode;
			};
			setSessionMode: {
				params: { sessionId: string; mode: SessionMode };
				response: SessionMode;
			};
			getSessionName: {
				params: { sessionId: string };
				response: string | null;
			};
			setSessionName: {
				params: { sessionId: string; name: string };
				response: string;
			};
			compactSessionHistory: {
				params: { sessionId: string };
				response: SessionHistoryCompactionResult;
			};
			setSessionApproveAll: {
				params: { sessionId: string; enabled: boolean };
				response: boolean;
			};
			resetSessionApprovals: {
				params: { sessionId: string };
				response: boolean;
			};
			getSettings: { params: Record<string, never>; response: Settings };
			updateSettings: { params: { next: Settings }; response: Settings };
			getLogDir: { params: Record<string, never>; response: string };
			openLogFolder: {
				params: Record<string, never>;
				response: boolean;
			};
			// Lets the webview pipe console messages + uncaught errors back
			// through the existing RPC channel so they show up in bun's
			// JSON log even when WebView2 devtools is closed. Pure
			// diagnostic — not part of any product surface.
			rendererLog: {
				params: {
					level: "debug" | "info" | "warn" | "error";
					message: string;
					extra?: Record<string, unknown>;
				};
				response: void;
			};
		};
		messages: Record<string, never>;
	}>;
	webview: RPCSchema<{
		requests: Record<string, never>;
		messages: {
			sessionEvent: SessionEventPayload;
		};
	}>;
};

export type { AppErrorPayload };
